config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new]
  resources :applications, only: [:create]
  resource :session, only: [:create, :new, :destroy]
  resources :jobs, only: [:index, :create, :new, ]

  root to: redirect('/jobs')

end

app/models/application.rb
# == Schema Information
#
# Table name: applications
#
#  id      :bigint(8)        not null, primary key
#  job_id  :integer          not null
#  user_id :integer          not null
#

class Application < ApplicationRecord
  validates :job_id, :user_id, presence: true
  belongs_to :job
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :string           not null
#  employer_id :integer          not null
#

class Job < ApplicationRecord
  validates :title, :description, :employer_id, presence: true

  has_many :applications
  has_many :applicants,
    through: :applications,
    source: :user
  belongs_to :employer,
    foreign_key: :employer_id,
    class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  user_type       :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :username, :email, :password_digest, :user_type, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :applications
  has_many :job_listings,
    foreign_key: :employer_id,
    class_name: :Job
  has_many :jobs_applied_to,
    through: :applications,
    source: :job
  has_many :job_applicants,
    through: :job_listings,
    source: :applicants

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def create
    @application = Application.new(application_params)
    if @application.save
      redirect_to jobs_url
      else
      flash[:errors] = @job.errors.full_messages
      redirect_to jobs_url
    end
  end
  
  def application_params
    params.require(:application).permit(:user_id, :job_id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_url
      else
      flash[:errors] = @job.errors.full_messages
      redirect_to jobs_url
    end
  end

  def job_params
    params.require(:job).permit(:title, :description, :employer_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user
      login(user)
      redirect_to jobs_url
    else
      flash.now[:errors] = ['Unable to create session']
      render :new
    end
  end

  def new
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to jobs_url
      else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :user_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<!-- job index -->
<!-- @jobs includes all of the job active records -->
<!-- current_user.job_applicants includes all of the users who have applied
  to all current employer's jobs if current_user is an employer-->

<% if @jobs && current_user.user_type == 'applicant'%>
<h2>Job Index</h2>
<ul>
  <% @jobs.each do |job|%>
    <li><%=job.title%></li>
    <li><%=job.description%></li>
    <li><%=job.employer.username%></li>
    <% unless job.applicants.include?(current_user) %>
      <form action="<%=applications_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="hidden" name="application[job_id]" value="<%= job.id %>">
        <input type="hidden" name="application[user_id]" value="<%= current_user.id %>">
        <input type="submit" name="" value="Apply">
      </form>
    <% end %>
    <br/>
  <% end %>
</ul>
<% end %>

<% if current_user.user_type == 'employer' %>
  <h2>Post a job</h2>
  <form class="" action="<%= jobs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input id="title" type="text" name="job[title]" value="" placeholder="Title">
    <input id="description" type="text" name="job[description]" value="" placeholder="Description">
    <input id = "employer_id" type="hidden" name="job[employer_id]" value="<%= current_user.id %>">
    <input type="submit" name="" value="Post this job">
  </form>
  <br/>
  <% if current_user.job_applicants %>
    <h2>These applicants have applied to your job listings</h2>
      <ul>
        <% current_user.job_applicants.each do |applicant|%>
          <li><%= applicant.username %></li>
        <% end %>
      </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fountain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      <form class="" action="<%= session_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Sign Out">
      </form>
      <% else %>
      <a href="<%= new_session_url%>">Sign In</a>
      <a href="<%= new_user_url%>">Sign Up</a>
    <% end %>

    <% if flash[:errors] %>
      <ul>
        <%flash[:errors].each do |el|%>
          <li><%=el%></li>
        <% end %>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<!-- "users new" -->
<h2>Sign Up</h2>
<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input id="username" type="text" name="user[username]" value="" placeholder="Username">
  <input id="username" type="text" name="user[email]" value="" placeholder="Email">
  <input id = "password" type="password" name="user[password]" value="" placeholder="Password">
  <label for="user_type">I am an: </label>
  <select name="user[user_type]">
    <option selected value="applicant">Applicant</option>
    <option value="employer">Employer</option>
  </select>
  <input type="submit" name="" value="Sign Up">
</form>